### ISSUE TITLE
Fatal Error!!!

### ISSUE THREAD

**Issue by mekler** [spaceship-labs/ctgen#5]
Intenté correr el comando tal cual y me generó este error.
```
➜  bin git:(master) ./ctgen.js install -d compranet
use db compranet
{ [Error: xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'<!DOCTYP']
  traceback: 'Traceback (most recent call last):\n  File "/home/mekler/Documents/opintel/ctgen/node_modules/pyspreadsheet/python/excel_reader.py", lin
e 59, in main\n    wb = open_workbook(filename=file, on_demand=True)\n  File "/home/mekler/Documents/opintel/ctgen/node_modules/pyspreadsheet/python/x
lrd/__init__.py", line 159, in open_workbook\n    ragged_rows=ragged_rows,\n  File "/home/mekler/Documents/opintel/ctgen/node_modules/pyspreadsheet/py
thon/xlrd/book.py", line 91, in open_workbook_xls\n    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)\n  File "/home/mekler/Documents/opintel/ctgen/nod
e_modules/pyspreadsheet/python/xlrd/book.py", line 1271, in getbof\n    bof_error(\'Expected BOF record; found %r\' % self.mem[savpos:savpos+8])\n  Fi
le "/home/mekler/Documents/opintel/ctgen/node_modules/pyspreadsheet/python/xlrd/book.py", line 1265, in bof_error\n    raise XLRDError(\'Unsupported f
ormat, or corrupt file: \' + msg)\nxlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b\'<!DOCTYP\'\n',
  file: '/home/mekler/Documents/opintel/ctgen/bin/ctbook_files_xls/contrataciones/wwwgob.mx/shcp/acciones-y-programas/cartera-publica-de-inversion-162
87',
  id: 'open_workbook_failed' }
/home/mekler/Documents/opintel/ctgen/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                                   ^
Error: Callback was already called.
    at /home/mekler/Documents/opintel/ctgen/node_modules/async/lib/async.js:43:36
    at /home/mekler/Documents/opintel/ctgen/node_modules/async/lib/async.js:771:17
    at /home/mekler/Documents/opintel/ctgen/lib/format.js:175:11
    at null.<anonymous> (/home/mekler/Documents/opintel/ctgen/lib/format.js:134:5)
    at emit (events.js:104:17)
    at null.<anonymous> (/home/mekler/Documents/opintel/ctgen/node_modules/pyspreadsheet/lib/spreadsheet-reader.js:104:14)
    at emit (events.js:104:17)
    at terminateIfNeeded (/home/mekler/Documents/opintel/ctgen/node_modules/pyspreadsheet/node_modules/python-shell/index.js:115:14)
    at ChildProcess.<anonymous> (/home/mekler/Documents/opintel/ctgen/node_modules/pyspreadsheet/node_modules/python-shell/index.js:88:9)
    at ChildProcess.emit (events.js:110:17)```

**Comment by urielaero** [comment]
Ya corregí el error, si no quieres volver a ejecutar todo desde el inicio puedes borrar los archivos:
ctbook_files_xls/contrataciones/upcpfuncionpublicagobmxdescargasPAIS.xlsx
ctbook_files_xls/contrataciones/wwwgob.mx
y ejecutar: 
`$ ctgen.js install -d compranet --xlsx ctbook_files_xls`
